#!/bin/bash

# Check if its enabled already
MULTI_SIM_DATA_CALL=$(adb shell settings get global multi_sim_data_call)

if [[ "$MULTI_SIM_DATA_CALL" -eq 2 ]]; then
    echo "its already enabled"
    exit 0
fi

# Check if the screen is off (mDreamingLockscreen=true indicates screen off or locked)
SCREEN_STATE=$(adb shell dumpsys window | grep "mDreamingLockscreen")

if [[ "$SCREEN_STATE" == *"mDreamingLockscreen=true"* ]]; then
    echo "Screen is off. Running the script..."

    # swipe the home screen
    /usr/local/bin/adb shell input keyevent 82
    /bin/sleep 0.5
    /usr/local/bin/adb shell input keyevent 82

    /bin/sleep 0.5

    # home screen
    /usr/local/bin/adb shell input keyevent 3

    /bin/sleep 0.5

    /usr/local/bin/adb shell am force-stop com.android.settings

    /bin/sleep 0.5

    # wireless settings
    /usr/local/bin/adb shell am start -a android.settings.WIRELESS_SETTINGS

    /bin/sleep 1

    # enter SIMs
    /usr/local/bin/adb shell input tap 163 952

    /bin/sleep 1

    # Data preference 
    /usr/local/bin/adb shell input tap 132 1339

    /bin/sleep 1

    # Irancell 9389
    /usr/local/bin/adb shell input tap 183 1342

    /bin/sleep 1

    # go back to home screen
    /usr/local/bin/adb shell input keyevent 3

    # turn off display
    /bin/sleep 1 
    /usr/local/bin/adb shell input keyevent 26

else
    echo "Screen is on. Exiting script."
fi
