#!/bin/bash
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponde

# flush cache on chrome:
# chrome://net-internals/#dns -> clear host cache
# chrome://net-internals/#sockets -> close idle sockets and flush socket pools
