#!/bin/bash


# moving the original vimrc to created backup folder

mkdir /tmp/backup
mv /usr/share/vim/vimrc /tmp/backup

# copy the vimrc from this file to vim folder

cp vimrc /usr/share/vim
echo "Done"
